### User - Buscar todos os usuários
GET http://localhost:8080/user

### User - Criar um usuário
POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "Paolo",
  "email": "pt@teste.com",
  "phone": "999999999",
  "cpf": "99999999999",
  "password": "teste"
}

### State - Buscar todos os estados
GET http://localhost:8080/state