version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    volumes:
    - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
